version: 2.1

executors:
    grid2op-executor:
        docker:
            - image: python:3.10
        working_directory: /Grid2Op

    python37:
        docker:
            - image: python:3.7
    python38:
        docker:
            - image: python:3.8
    python39:
        docker:
            - image: python:3.9
    python310:
        docker:
            - image: python:3.10
    python311:
        docker:
            - image: python:3.11
    python312:
        docker:
            - image: cimg/python:3.12

jobs:
    test:
        executor: grid2op-executor
        resource_class: medium+
        parallelism: 4
        steps:
            - checkout
            - run: apt-get update -y
            - run: apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U pip setuptools wheel
            - run:
                command: |
                  source venv_test/bin/activate
                  pip install -e .[test]
                  export _GRID2OP_FORCE_TEST=1
                  cd grid2op/tests/
                  python3 helper_list_test.py | circleci tests split > /tmp/tests_run
            - run:
                command: |
                  source venv_test/bin/activate
                  pip freeze
            - run: cat /tmp/tests_run
            - run:
                command: |
                  source venv_test/bin/activate
                  cd grid2op/tests/
                  export _GRID2OP_FORCE_TEST=1
                  python3 -m unittest -v $(cat /tmp/tests_run)
                  
    install36:
        executor: python36
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U pip setuptools wheel
            - run:
                command: |
                    source venv_test/bin/activate
                    pip install -U numba
                    pip install -U "numpy>=1.18,<1.19"
                    pip install -U .[test]
                    export _GRID2OP_FORCE_TEST=1
                    grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   pip install -U "numpy>=1.19,<1.20"
                   pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
                   
    install37:
        executor: python37
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U numba
                   python -m pip install -U "numpy>=1.20,<1.21"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.21,<1.22"
                   python -m pip install -U .[test]
                   export _GRID2OP_FORCE_TEST=1
                   grid2op.testinstall

    install38:               
        executor: python38
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
                   python -m pip install -U numba
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.20,<1.21" "pandas<2.2" "scipy<1.12" numba .[test]
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.24,<1.25" "pandas<2.2" "scipy<1.12" numba .[test]
            - run:
                command: |
                   source venv_test/bin/activate
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall

    legacy_lightsim:               
        executor: python38  # needs to be 38: whl of lightsim were not released for 3.10 at the time
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
                   python -m pip install -U lightsim2grid==0.5.3 gymnasium "numpy<1.22"
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -e .
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   python -m unittest grid2op/tests/test_basic_env_ls.py

    install39:
        executor: python39
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   export _GRID2OP_FORCE_TEST=1
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel "numpy>=1.20,<1.21" "pandas<2.2" "scipy==1.10.1" numba
                   python -m pip install "chronix2grid>=1.1.0.post1" "gymnasium==0.26.3" "matplotlib==3.7.5" "xarray==2023.10.0" "scs==3.0.0" "ecos==2.0.0"
                   python -m pip uninstall -y grid2op
            - run:
               command: |  # issue with previous more simple install, so I fix some versions
                   source venv_test/bin/activate
                   python -m pip install "numpy>=1.20,<1.21" "pandas<2.2" "scipy==1.10.1" numba .
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install "numpy>=1.26,<1.27" "pandas<2.2" "scipy<1.12" numba
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall

    install310:
        executor: python310
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
                   python -m pip install -U numba
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.21,<1.22" "pandas<2.2" "scipy<1.12" numba .
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.26,<1.27" "pandas<2.2" "scipy<1.12" numba
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall

    install311:
        executor: python311
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    apt-get update
                    apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.23,<1.24" "pandas<2.2" "scipy<1.12" numba .
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.26,<1.27" "pandas<2.2" "scipy<1.12" numba
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall
    install312:
        executor: python312
        resource_class: small
        steps:
            - checkout
            - run: 
                command: |
                    sudo  apt-get update
                    sudo  apt-get install -y coinor-cbc
            - run: python -m pip install virtualenv
            - run: python -m virtualenv venv_test
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U pip setuptools wheel
                #    python -m pip install -U numba  # not on python 3.12 at the moment
            - run:
               command: |
                   source venv_test/bin/activate
                   python -m pip install -U "numpy>=1.26,<1.27" "pandas<2.2" "scipy<1.12" .
                   pip freeze
            - run:
                command: |
                   source venv_test/bin/activate
                   export _GRID2OP_FORCE_TEST=1
                   cd /tmp
                   grid2op.testinstall

workflows:
    version: 2.1
    test:
        jobs:
          - test
          - legacy_lightsim
    install:
        jobs:
          - install38
          - install39
          - install310
          - install311
          - install312
